'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WSProductos
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RetailContext", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RetailContext
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DatabaseIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DatabaseId() As String
            Get
                Return Me.DatabaseIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DatabaseIdField, value) <> true) Then
                    Me.DatabaseIdField = value
                    Me.RaisePropertyChanged("DatabaseId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WSProductos.BusinessFaultDetail))>  _
    Partial Public Class CbpFaultDetail
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceLocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToDoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceLocation() As String
            Get
                Return Me.SourceLocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceLocationField, value) <> true) Then
                    Me.SourceLocationField = value
                    Me.RaisePropertyChanged("SourceLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToDo() As String
            Get
                Return Me.ToDoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToDoField, value) <> true) Then
                    Me.ToDoField = value
                    Me.RaisePropertyChanged("ToDo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BusinessFaultDetail
        Inherits WSProductos.CbpFaultDetail
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MemberNamesField() As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MemberNames() As String()
            Get
                Return Me.MemberNamesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MemberNamesField, value) <> true) Then
                    Me.MemberNamesField = value
                    Me.RaisePropertyChanged("MemberNames")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(WSProductos.CbpExceptionDetail))>  _
    Partial Public Class ExceptionDetail
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HelpLinkField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InnerExceptionField As WSProductos.ExceptionDetail
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TrackingIdField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property HelpLink() As String
            Get
                Return Me.HelpLinkField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HelpLinkField, value) <> true) Then
                    Me.HelpLinkField = value
                    Me.RaisePropertyChanged("HelpLink")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property InnerException() As WSProductos.ExceptionDetail
            Get
                Return Me.InnerExceptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InnerExceptionField, value) <> true) Then
                    Me.InnerExceptionField = value
                    Me.RaisePropertyChanged("InnerException")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TrackingId() As System.Nullable(Of System.Guid)
            Get
                Return Me.TrackingIdField
            End Get
            Set
                If (Me.TrackingIdField.Equals(value) <> true) Then
                    Me.TrackingIdField = value
                    Me.RaisePropertyChanged("TrackingId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As String
            Get
                Return Me.TypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeField, value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CbpExceptionDetail
        Inherits WSProductos.ExceptionDetail
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToDoField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToDo() As String
            Get
                Return Me.ToDoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToDoField, value) <> true) Then
                    Me.ToDoField = value
                    Me.RaisePropertyChanged("ToDo")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ItemIdentifier", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ItemIdentifier
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferenceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Reference() As String
            Get
                Return Me.ReferenceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferenceField, value) <> true) Then
                    Me.ReferenceField = value
                    Me.RaisePropertyChanged("Reference")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AvailableQtyReturn", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AvailableQtyReturn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AvailableQtyField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QueryStatusField As WSProductos.QueryExecutionStatus
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AvailableQty() As Decimal
            Get
                Return Me.AvailableQtyField
            End Get
            Set
                If (Me.AvailableQtyField.Equals(value) <> true) Then
                    Me.AvailableQtyField = value
                    Me.RaisePropertyChanged("AvailableQty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property QueryStatus() As WSProductos.QueryExecutionStatus
            Get
                Return Me.QueryStatusField
            End Get
            Set
                If (Me.QueryStatusField.Equals(value) <> true) Then
                    Me.QueryStatusField = value
                    Me.RaisePropertyChanged("QueryStatus")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="QueryExecutionStatus", [Namespace]:="http://www.cegid.fr/Retail/1.0")>  _
    Public Enum QueryExecutionStatus As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Ok = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IncorrectWarehouseId = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IncorrectStoreId = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        StoreNotFound = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unknown = 4
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AvailableQtyByStore", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AvailableQtyByStore
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AvailableQtyField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StoreDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StoreIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AvailableQty() As Decimal
            Get
                Return Me.AvailableQtyField
            End Get
            Set
                If (Me.AvailableQtyField.Equals(value) <> true) Then
                    Me.AvailableQtyField = value
                    Me.RaisePropertyChanged("AvailableQty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StoreDescription() As String
            Get
                Return Me.StoreDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StoreDescriptionField, value) <> true) Then
                    Me.StoreDescriptionField = value
                    Me.RaisePropertyChanged("StoreDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StoreId() As String
            Get
                Return Me.StoreIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StoreIdField, value) <> true) Then
                    Me.StoreIdField = value
                    Me.RaisePropertyChanged("StoreId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateShoppingCart_Request", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateShoppingCart_Request
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private ItemIdentifierField As WSProductos.ItemIdentifier
        
        Private QuantityField As Decimal
        
        Private WarehouseIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ItemIdentifier() As WSProductos.ItemIdentifier
            Get
                Return Me.ItemIdentifierField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemIdentifierField, value) <> true) Then
                    Me.ItemIdentifierField = value
                    Me.RaisePropertyChanged("ItemIdentifier")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Quantity() As Decimal
            Get
                Return Me.QuantityField
            End Get
            Set
                If (Me.QuantityField.Equals(value) <> true) Then
                    Me.QuantityField = value
                    Me.RaisePropertyChanged("Quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property WarehouseId() As String
            Get
                Return Me.WarehouseIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WarehouseIdField, value) <> true) Then
                    Me.WarehouseIdField = value
                    Me.RaisePropertyChanged("WarehouseId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResetShoppingCart_Request", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResetShoppingCart_Request
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemIdentifierField As WSProductos.ItemIdentifier
        
        Private WarehouseIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ItemIdentifier() As WSProductos.ItemIdentifier
            Get
                Return Me.ItemIdentifierField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemIdentifierField, value) <> true) Then
                    Me.ItemIdentifierField = value
                    Me.RaisePropertyChanged("ItemIdentifier")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property WarehouseId() As String
            Get
                Return Me.WarehouseIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WarehouseIdField, value) <> true) Then
                    Me.WarehouseIdField = value
                    Me.RaisePropertyChanged("WarehouseId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetListItemInventoryDetailByStore_Request", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetListItemInventoryDetailByStore_Request
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AllAvailableWarehouseField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DetailSkuField As Boolean
        
        Private ItemIdentifiersField() As WSProductos.ItemIdentifier
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OnlyAvailableStockField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PagerField As WSProductos.Pager
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StoreIdsField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WithStoreNameField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AllAvailableWarehouse() As Boolean
            Get
                Return Me.AllAvailableWarehouseField
            End Get
            Set
                If (Me.AllAvailableWarehouseField.Equals(value) <> true) Then
                    Me.AllAvailableWarehouseField = value
                    Me.RaisePropertyChanged("AllAvailableWarehouse")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DetailSku() As Boolean
            Get
                Return Me.DetailSkuField
            End Get
            Set
                If (Me.DetailSkuField.Equals(value) <> true) Then
                    Me.DetailSkuField = value
                    Me.RaisePropertyChanged("DetailSku")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ItemIdentifiers() As WSProductos.ItemIdentifier()
            Get
                Return Me.ItemIdentifiersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemIdentifiersField, value) <> true) Then
                    Me.ItemIdentifiersField = value
                    Me.RaisePropertyChanged("ItemIdentifiers")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OnlyAvailableStock() As Boolean
            Get
                Return Me.OnlyAvailableStockField
            End Get
            Set
                If (Me.OnlyAvailableStockField.Equals(value) <> true) Then
                    Me.OnlyAvailableStockField = value
                    Me.RaisePropertyChanged("OnlyAvailableStock")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pager() As WSProductos.Pager
            Get
                Return Me.PagerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PagerField, value) <> true) Then
                    Me.PagerField = value
                    Me.RaisePropertyChanged("Pager")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StoreIds() As String()
            Get
                Return Me.StoreIdsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StoreIdsField, value) <> true) Then
                    Me.StoreIdsField = value
                    Me.RaisePropertyChanged("StoreIds")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property WithStoreName() As Boolean
            Get
                Return Me.WithStoreNameField
            End Get
            Set
                If (Me.WithStoreNameField.Equals(value) <> true) Then
                    Me.WithStoreNameField = value
                    Me.RaisePropertyChanged("WithStoreName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Pager", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Pager
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageIndexField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PageSizeField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageIndex() As Integer
            Get
                Return Me.PageIndexField
            End Get
            Set
                If (Me.PageIndexField.Equals(value) <> true) Then
                    Me.PageIndexField = value
                    Me.RaisePropertyChanged("PageIndex")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PageSize() As Integer
            Get
                Return Me.PageSizeField
            End Get
            Set
                If (Me.PageSizeField.Equals(value) <> true) Then
                    Me.PageSizeField = value
                    Me.RaisePropertyChanged("PageSize")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GetListItemInventoryDetailByStore_Reply", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GetListItemInventoryDetailByStore_Reply
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InventoryDetailsByStoreField() As WSProductos.AvailableQtyByItemByStore
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InventoryDetailsByStore() As WSProductos.AvailableQtyByItemByStore()
            Get
                Return Me.InventoryDetailsByStoreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InventoryDetailsByStoreField, value) <> true) Then
                    Me.InventoryDetailsByStoreField = value
                    Me.RaisePropertyChanged("InventoryDetailsByStore")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AvailableQtyByItemByStore", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AvailableQtyByItemByStore
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StoresAvailableQtyField() As WSProductos.StoreAvailableQty
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ItemCode() As String
            Get
                Return Me.ItemCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemCodeField, value) <> true) Then
                    Me.ItemCodeField = value
                    Me.RaisePropertyChanged("ItemCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StoresAvailableQty() As WSProductos.StoreAvailableQty()
            Get
                Return Me.StoresAvailableQtyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StoresAvailableQtyField, value) <> true) Then
                    Me.StoresAvailableQtyField = value
                    Me.RaisePropertyChanged("StoresAvailableQty")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StoreAvailableQty", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class StoreAvailableQty
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AvailableQuantityField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AvailableSkusQtyField() As WSProductos.AvailableSkuQty
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StoreIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StoreNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AvailableQuantity() As Decimal
            Get
                Return Me.AvailableQuantityField
            End Get
            Set
                If (Me.AvailableQuantityField.Equals(value) <> true) Then
                    Me.AvailableQuantityField = value
                    Me.RaisePropertyChanged("AvailableQuantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AvailableSkusQty() As WSProductos.AvailableSkuQty()
            Get
                Return Me.AvailableSkusQtyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AvailableSkusQtyField, value) <> true) Then
                    Me.AvailableSkusQtyField = value
                    Me.RaisePropertyChanged("AvailableSkusQty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StoreId() As String
            Get
                Return Me.StoreIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StoreIdField, value) <> true) Then
                    Me.StoreIdField = value
                    Me.RaisePropertyChanged("StoreId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property StoreName() As String
            Get
                Return Me.StoreNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StoreNameField, value) <> true) Then
                    Me.StoreNameField = value
                    Me.RaisePropertyChanged("StoreName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AvailableSkuQty", [Namespace]:="http://www.cegid.fr/Retail/1.0"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AvailableSkuQty
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AvailableQtyField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Dimension1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Dimension2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Dimension3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Dimension4Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Dimension5Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AvailableQty() As Decimal
            Get
                Return Me.AvailableQtyField
            End Get
            Set
                If (Me.AvailableQtyField.Equals(value) <> true) Then
                    Me.AvailableQtyField = value
                    Me.RaisePropertyChanged("AvailableQty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Dimension1() As String
            Get
                Return Me.Dimension1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Dimension1Field, value) <> true) Then
                    Me.Dimension1Field = value
                    Me.RaisePropertyChanged("Dimension1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Dimension2() As String
            Get
                Return Me.Dimension2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Dimension2Field, value) <> true) Then
                    Me.Dimension2Field = value
                    Me.RaisePropertyChanged("Dimension2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Dimension3() As String
            Get
                Return Me.Dimension3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Dimension3Field, value) <> true) Then
                    Me.Dimension3Field = value
                    Me.RaisePropertyChanged("Dimension3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Dimension4() As String
            Get
                Return Me.Dimension4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Dimension4Field, value) <> true) Then
                    Me.Dimension4Field = value
                    Me.RaisePropertyChanged("Dimension4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Dimension5() As String
            Get
                Return Me.Dimension5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Dimension5Field, value) <> true) Then
                    Me.Dimension5Field = value
                    Me.RaisePropertyChanged("Dimension5")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.cegid.fr/Retail/1.0", ConfigurationName:="WSProductos.IItemInventoryWcfService")>  _
    Public Interface IItemInventoryWcfService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorld", ReplyAction:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorldResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorldCbpFaultDet"& _ 
            "ailFault", Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.BusinessFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorldBusinessFau"& _ 
            "ltDetailFault", Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.ExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorldExceptionDe"& _ 
            "tailFault", Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorldCbpExceptio"& _ 
            "nDetailFault", Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault")>  _
        Function HelloWorld(ByVal text As String, ByVal clientContext As WSProductos.RetailContext) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorld", ReplyAction:="http://www.cegid.fr/Retail/1.0/ICbrBasicWebServiceInterface/HelloWorldResponse")>  _
        Function HelloWorldAsync(ByVal text As String, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQty", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQtyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQtyCbpFaultDe"& _ 
            "tailFault", Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.BusinessFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQtyBusinessFa"& _ 
            "ultDetailFault", Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.ExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQtyExceptionD"& _ 
            "etailFault", Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQtyCbpExcepti"& _ 
            "onDetailFault", Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault")>  _
        Function GetAvailableQty(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal storeId As String, ByVal warehouseId As String, ByVal clientContext As WSProductos.RetailContext) As WSProductos.AvailableQtyReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQty", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableQtyResponse")>  _
        Function GetAvailableQtyAsync(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal storeId As String, ByVal warehouseId As String, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.AvailableQtyReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStores", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStoresResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStoresCbpFaultDetailFault", Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.BusinessFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStoresBusinessFaultDetailFault", Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.ExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStoresExceptionDetailFault", Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStoresCbpExceptionDetailFault", Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault")>  _
        Function GetAvailableCumulativeQtyAllStores(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As WSProductos.AvailableQtyReturn
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStores", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetAvailableCumulativeQty"& _ 
            "AllStoresResponse")>  _
        Function GetAvailableCumulativeQtyAllStoresAsync(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.AvailableQtyReturn)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "Response"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "CbpFaultDetailFault", Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.BusinessFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "BusinessFaultDetailFault", Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.ExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "ExceptionDetailFault", Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "CbpExceptionDetailFault", Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault")>  _
        Function GetInventoryDetailByStore(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As WSProductos.AvailableQtyByStore()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetInventoryDetailByStore"& _ 
            "Response")>  _
        Function GetInventoryDetailByStoreAsync(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.AvailableQtyByStore())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCart", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCartRespons"& _ 
            "e"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCartCbpFaul"& _ 
            "tDetailFault", Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.BusinessFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCartBusines"& _ 
            "sFaultDetailFault", Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.ExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCartExcepti"& _ 
            "onDetailFault", Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCartCbpExce"& _ 
            "ptionDetailFault", Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault")>  _
        Sub UpdateShoppingCart(ByVal request As WSProductos.UpdateShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCart", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/UpdateShoppingCartRespons"& _ 
            "e")>  _
        Function UpdateShoppingCartAsync(ByVal request As WSProductos.UpdateShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCart", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCartResponse"& _ 
            ""),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCartCbpFault"& _ 
            "DetailFault", Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.BusinessFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCartBusiness"& _ 
            "FaultDetailFault", Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.ExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCartExceptio"& _ 
            "nDetailFault", Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCartCbpExcep"& _ 
            "tionDetailFault", Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault")>  _
        Sub ResetShoppingCart(ByVal request As WSProductos.ResetShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCart", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/ResetShoppingCartResponse"& _ 
            "")>  _
        Function ResetShoppingCartAsync(ByVal request As WSProductos.ResetShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStore", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStoreResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStoreCbpFaultDetailFault", Name:="CbpFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.BusinessFaultDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStoreBusinessFaultDetailFault", Name:="BusinessFaultDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.ExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStoreExceptionDetailFault", Name:="ExceptionDetail", [Namespace]:="http://www.cegid.fr/fault"),  _
         System.ServiceModel.FaultContractAttribute(GetType(WSProductos.CbpExceptionDetail), Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStoreCbpExceptionDetailFault", Name:="CbpExceptionDetail", [Namespace]:="http://www.cegid.fr/fault")>  _
        Function GetListItemInventoryDetailByStore(ByVal inventoryStoreItemDetailRequest As WSProductos.GetListItemInventoryDetailByStore_Request, ByVal clientContext As WSProductos.RetailContext) As WSProductos.GetListItemInventoryDetailByStore_Reply
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStore", ReplyAction:="http://www.cegid.fr/Retail/1.0/IItemInventoryWcfService/GetListItemInventoryDetai"& _ 
            "lByStoreResponse")>  _
        Function GetListItemInventoryDetailByStoreAsync(ByVal inventoryStoreItemDetailRequest As WSProductos.GetListItemInventoryDetailByStore_Request, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.GetListItemInventoryDetailByStore_Reply)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IItemInventoryWcfServiceChannel
        Inherits WSProductos.IItemInventoryWcfService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ItemInventoryWcfServiceClient
        Inherits System.ServiceModel.ClientBase(Of WSProductos.IItemInventoryWcfService)
        Implements WSProductos.IItemInventoryWcfService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld(ByVal text As String, ByVal clientContext As WSProductos.RetailContext) As String Implements WSProductos.IItemInventoryWcfService.HelloWorld
            Return MyBase.Channel.HelloWorld(text, clientContext)
        End Function
        
        Public Function HelloWorldAsync(ByVal text As String, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of String) Implements WSProductos.IItemInventoryWcfService.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(text, clientContext)
        End Function
        
        Public Function GetAvailableQty(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal storeId As String, ByVal warehouseId As String, ByVal clientContext As WSProductos.RetailContext) As WSProductos.AvailableQtyReturn Implements WSProductos.IItemInventoryWcfService.GetAvailableQty
            Return MyBase.Channel.GetAvailableQty(itemId, itemIdentifier, storeId, warehouseId, clientContext)
        End Function
        
        Public Function GetAvailableQtyAsync(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal storeId As String, ByVal warehouseId As String, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.AvailableQtyReturn) Implements WSProductos.IItemInventoryWcfService.GetAvailableQtyAsync
            Return MyBase.Channel.GetAvailableQtyAsync(itemId, itemIdentifier, storeId, warehouseId, clientContext)
        End Function
        
        Public Function GetAvailableCumulativeQtyAllStores(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As WSProductos.AvailableQtyReturn Implements WSProductos.IItemInventoryWcfService.GetAvailableCumulativeQtyAllStores
            Return MyBase.Channel.GetAvailableCumulativeQtyAllStores(itemId, itemIdentifier, clientContext)
        End Function
        
        Public Function GetAvailableCumulativeQtyAllStoresAsync(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.AvailableQtyReturn) Implements WSProductos.IItemInventoryWcfService.GetAvailableCumulativeQtyAllStoresAsync
            Return MyBase.Channel.GetAvailableCumulativeQtyAllStoresAsync(itemId, itemIdentifier, clientContext)
        End Function
        
        Public Function GetInventoryDetailByStore(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As WSProductos.AvailableQtyByStore() Implements WSProductos.IItemInventoryWcfService.GetInventoryDetailByStore
            Return MyBase.Channel.GetInventoryDetailByStore(itemId, itemIdentifier, clientContext)
        End Function
        
        Public Function GetInventoryDetailByStoreAsync(ByVal itemId As String, ByVal itemIdentifier As WSProductos.ItemIdentifier, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.AvailableQtyByStore()) Implements WSProductos.IItemInventoryWcfService.GetInventoryDetailByStoreAsync
            Return MyBase.Channel.GetInventoryDetailByStoreAsync(itemId, itemIdentifier, clientContext)
        End Function
        
        Public Sub UpdateShoppingCart(ByVal request As WSProductos.UpdateShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext) Implements WSProductos.IItemInventoryWcfService.UpdateShoppingCart
            MyBase.Channel.UpdateShoppingCart(request, clientContext)
        End Sub
        
        Public Function UpdateShoppingCartAsync(ByVal request As WSProductos.UpdateShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task Implements WSProductos.IItemInventoryWcfService.UpdateShoppingCartAsync
            Return MyBase.Channel.UpdateShoppingCartAsync(request, clientContext)
        End Function
        
        Public Sub ResetShoppingCart(ByVal request As WSProductos.ResetShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext) Implements WSProductos.IItemInventoryWcfService.ResetShoppingCart
            MyBase.Channel.ResetShoppingCart(request, clientContext)
        End Sub
        
        Public Function ResetShoppingCartAsync(ByVal request As WSProductos.ResetShoppingCart_Request, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task Implements WSProductos.IItemInventoryWcfService.ResetShoppingCartAsync
            Return MyBase.Channel.ResetShoppingCartAsync(request, clientContext)
        End Function
        
        Public Function GetListItemInventoryDetailByStore(ByVal inventoryStoreItemDetailRequest As WSProductos.GetListItemInventoryDetailByStore_Request, ByVal clientContext As WSProductos.RetailContext) As WSProductos.GetListItemInventoryDetailByStore_Reply Implements WSProductos.IItemInventoryWcfService.GetListItemInventoryDetailByStore
            Return MyBase.Channel.GetListItemInventoryDetailByStore(inventoryStoreItemDetailRequest, clientContext)
        End Function
        
        Public Function GetListItemInventoryDetailByStoreAsync(ByVal inventoryStoreItemDetailRequest As WSProductos.GetListItemInventoryDetailByStore_Request, ByVal clientContext As WSProductos.RetailContext) As System.Threading.Tasks.Task(Of WSProductos.GetListItemInventoryDetailByStore_Reply) Implements WSProductos.IItemInventoryWcfService.GetListItemInventoryDetailByStoreAsync
            Return MyBase.Channel.GetListItemInventoryDetailByStoreAsync(inventoryStoreItemDetailRequest, clientContext)
        End Function
    End Class
End Namespace
